version: "3.9"

services:
  db:
    image: postgres:16
    container_name: vocab-master-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vocab
      POSTGRES_PASSWORD: vocab_password
      POSTGRES_DB: vocab_master
    ports:
      - "6543:5432"
    volumes:
      - vocab_master_pg:/var/lib/postgresql/data

volumes:
  vocab_master_pg:
